# This file was generated by GoReleaser. DO NOT EDIT.
cask "baseliner" do
  version "0.2.6"

  on_macos do
    on_arm do
      sha256 "315efa2a1ecca7de6703d1f022f5614851d0f84bdd38ed84aba7061898551a84"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e59517987f314f8232988f00c3375747a25358a58e52bff48cc2a7517e35ee75"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3d2c72117bd5b486c6f6091f1c25ad98d9b5bbd997b80236b6ef2e4a5656fc5"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2bdab6e7517364d95df656e860c00dee1c6944327b878986982285f2a723c99"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_amd64.tar.gz"
    end
  end

  name "baseliner"
  desc "Repository fleet baseline compliance engine"
  homepage "https://github.com/baselinerhq/baseliner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baseliner"

  # No zap stanza required
end
