# This file was generated by GoReleaser. DO NOT EDIT.
cask "baseliner" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "79ec5f50efeeebb7d736781647aec7e1480368875270b7a3b902dc63a58b3291"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "447997e85e0ff021502cf76e2b6206cb5ab0bd89cb9f7896e90bf791296b2d18"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e5cefb264fb2180837b44288b071cec3718a7f17a7b7c44ba70aef4e10d156ce"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3459a266f0c21eeb698145d3728cd4b56d7890e3b37848c6c6f293db8eca411a"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_arm64.tar.gz"
    end
  end

  name "baseliner"
  desc "Repository fleet baseline compliance engine"
  homepage "https://github.com/baselinerhq/baseliner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baseliner"

  # No zap stanza required

end
