# This file was generated by GoReleaser. DO NOT EDIT.
cask "baseliner" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "832868927aa6935007f4e60683e455e4c2fd5a2fc7e219970950ef75d9688c3f"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8fb4b6ff2b826a5574c3427b07b29a994efbeab470e178492036ad93a6d1691f"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a5409378a41bcac9cb3b91490400328e639a0ebc89b9b8393a36df613aaa52e9"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f30bf2c1f4bf70250e6e1861f08514cbc5360bb459e5e335252f8e9a4b3b4ee"
      url "https://github.com/baselinerhq/baseliner/releases/download/v#{version}/baseliner_linux_arm64.tar.gz"
    end
  end

  name "baseliner"
  desc "Repository fleet baseline compliance engine"
  homepage "https://github.com/baselinerhq/baseliner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baseliner"

  # No zap stanza required

end
